# Generated by Django 3.2 on 2021-04-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_number', models.PositiveIntegerField()),
                ('extroversion', models.BooleanField(default=False)),
                ('agreeableness', models.BooleanField(default=False)),
                ('conscientiousness', models.BooleanField(default=False)),
                ('neuroticism', models.BooleanField(default=False)),
                ('openness_to_experience', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
