# Generated by Django 3.2 on 2021-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_number', models.PositiveIntegerField()),
                ('extroversion', models.BooleanField(default=False)),
                ('agreeableness', models.BooleanField(default=False)),
                ('conscientiousness', models.BooleanField(default=False)),
                ('neuroticism', models.BooleanField(default=False)),
                ('openness_to_experience', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
