# Generated by Django 3.2 on 2021-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField(default=False)),
                ('two', models.BooleanField(default=False)),
                ('three', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('five', models.BooleanField(default=False)),
            ],
        ),
    ]
